language: perl
perl:
- 5.16.3
sudo: required
services:
- docker
before_install:
- cpanm -n Devel::Cover::Report::Coveralls
install:
- docker pull kbase/kb-sdk
- docker run kbase/kb-sdk genscript > $HOME/bin/kb-sdk
- chmod 755 $HOME/bin/kb-sdk
- export PATH=$PATH:$HOME/bin/kb-sdk
- kb-sdk sdkbase
- kb-sdk test || true
- make build-test-script
- sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
- sed -i 's/$(id -u)/0:0/' test_local/run_tests.sh
script:
- kb-sdk test
env:
  global:
    secure: eo5rM8HDGYigxbLeHqctZy3+Wx/wyTNOl1wqnElxXEFmaZ94xEfEcnHTK+PTXkQOXSwoXG0mOmPZCuG1ZKhtU3qP71TivEukf5iKCR4FY0VwXNjFGgLH/XGIDQizphrQWxeh/yJHJHEt1MskcKUK9wfarmHCJE3Xnjg/1MqNiyIRkSgYhFTvg6Vsi9bUvsjkslUZ7PsaRtL4Hu3ktalc8oDd4Y953ByjfZBZpiva2f+eydn2Dh1jE74p3rN6EdXK6gDSHQz6gFbBzzlJCX9AcWf3WxPaotBCpm1IrUcMt2EeWPDFTFCCRiRzWd/+AvdUwFxGpmFzDS8Enf442by4j+cuFzUqRnYESqPcVBM903vcuZVGH1tDEjk50eOLXmOOyf6/dSqbCduYAXGCFLHiX1Dd5VLdjYkFp4chR1ZmGrDrslAsqm1uBH+PdVbzghuRLU0jhTnWEO+eOuo8aapILkmjZRSRfEYsSZ2PpQP4oZddYkEOIUaal1yhUUluoSg8HVFM65LL2eswkSSGUVxIP59xtN/sh95zi/M9WUp0cRXLB+OxWcFrqPL30rV472IiWUiIYLRj08YtmoycxYiqJ2OSQUqWOeBJEUEFVzPm71rcNZGDd+P4d46teGVzxdN1Dm6OUSkAehEfr7B5YVwB/+AoEW9z6qC/KIzckY9XqD8=